management/models.py
from enum import unique
from management import db

class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    store_name = db.Column(db.String(200), nullable=False)
    order_list = db.Column(db.Text(), nullable=False)
    ordered_date = db.Column(db.DateTime(), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    user = db.relationship('User', backref=db.backref('order_set'))
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(200), nullable=False)
    phone_number = db.Column(db.String(120), unique=True, nullable=False)

management/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.fields.simple import PasswordField
from wtforms.validators import DataRequired, EqualTo, Length

class OrderForm(FlaskForm):
    store_name = StringField('가게명', validators=[DataRequired()])
    order_list = TextAreaField('주문 내용', validators=[DataRequired()])

class UserCreateForm(FlaskForm):
    username = StringField('이름', validators=[DataRequired(), Length(min=3, max=25)])
    password1 = PasswordField('비밀번호', validators=[DataRequired(), EqualTo('password2', '비밀번호가 일치하지 않습니다.')])
    password2 = PasswordField('비밀번호 확인', validators=[DataRequired()])
    phone_number = StringField('휴대폰 번호', validators=[DataRequired()])

class UserLoginForm(FlaskForm):
    username = StringField('이름', validators=[DataRequired(), Length(min=3, max=25)])
    password = PasswordField('비밀번호', validators=[DataRequired()])

management/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
import config
from sqlalchemy import MetaData

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
db = SQLAlchemy(metadata=MetaData(naming_convention=naming_convention))
migrate = Migrate()

def create_app():
    app = Flask(__name__)

    app.config.from_object(config)

    db.init_app(app)
    
    if app.config['SQLALCHEMY_DATABASE_URI'].startswith("sqlite"):
        migrate.init_app(app, db, render_as_batch=True)
    else:
        migrate.init_app(app, db)

    from . import models
    from .views import main_views, ordered_views, auth_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(ordered_views.bp)
    app.register_blueprint(auth_views.bp)
    
    return app

management/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from management import db
from management.forms import UserCreateForm, UserLoginForm


bp = Blueprint('auth', __name__, url_prefix='/auth')
from ..models import User
import functools


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        phone_number=form.phone_number.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

management/views/main_views.py
from flask import Blueprint, url_for
from werkzeug.utils import redirect

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def index():
    return redirect(url_for('ordered._list'))

management/views/ordered_views.py
from flask import Blueprint, render_template, request, url_for, g
from management.models import Order
from ..forms import OrderForm
from datetime import datetime
from werkzeug.utils import redirect
from .. import db
from management.views.auth_views import login_required


bp = Blueprint('ordered', __name__, url_prefix='/ordered')

@bp.route('/list/')
def _list():
    ordered_list = Order.query.group_by('store_name').order_by(Order.ordered_date.desc())
    return render_template('ordered/ordered_list.html', ordered_list=ordered_list)


@bp.route('detail/<string:ordered_store_name>/')
def detail(ordered_store_name):
    ordered = Order.query.filter_by(store_name=ordered_store_name).all()
    return render_template('ordered/ordered_detail.html', ordered=ordered)

@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def create():
    form = OrderForm()
    if request.method == 'POST' and form.validate_on_submit():
        order = Order(store_name=form.store_name.data, order_list=form.order_list.data, ordered_date=datetime.now(), user=g.user)
        db.session.add(order)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('ordered/order_form.html', form=form)

management/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>order management</title>
</head>
<body>
{% include "navbar.html" %}
{% block content %}
{% endblock %}

</body>

</html>

management/templates/form_errors.html
{% for field, errors in form.errors.items() %}
<div role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}

{% for message in get_flashed_messages() %}
<div role="alert">
    {{ message }}
</div>
{% endfor %}

management/templates/navbar.html
<nav>
    <a href="{{ url_for('main.index') }}">Order Management</a>
    <button type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
    </button>
    <div id="navbarNav">
        {% if g.user %}
        <ul>
            <li>
                <a href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
            </li>
        </ul>
        {% else %}
        <ul>
            <li>
                <a href="{{ url_for('auth.signup') }}">계정생성</a>
            </li>
            <li>
                <a href="{{ url_for('auth.login') }}">로그인</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>

management/templates/ordered/order_form.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h5>주문하기</h5>
    <form method="post">
        {{ form.csrf_token }}
        {% for field, errors in form.errors.items() %}
        <div role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}

        <div>
            <label for="store_name">가게명</label>
            <input type="text" name="store_name" id="store_name">
        </div>
        <div>
            <label for="order_list">주문 내용</label>
            <textarea name="order_list" id="order_list" rows="5"></textarea>
        </div>
        <button type="submit">주문</button>
    </form>
</div>
{% endblock %}

management/templates/ordered/ordered_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ ordered.store_name }}</h1>

<div>
    {% for order in ordered %}
    <table>
        <th>{{ loop.index }}</th>
        <td>{{ order.order_list }}</td>
        <td>{{ order.ordered_date }}</td>
    </table>
    {% endfor %}
    
</div>

{% endblock %}

management/templates/ordered/ordered_list.html
{% extends 'base.html' %}
{% block content %}

{% if ordered_list %}
    <ul>
    {% for ordered in ordered_list %}
        <li><a href="{{ url_for('ordered.detail', ordered_store_name=ordered.store_name) }}">{{ ordered.store_name }}</a></li>

    {% endfor %}
    </ul>
{% else %}
    <p>nothing ordered</p>
{% endif %}
<a href="{{ url_for('ordered.create') }}">Order!</a>

{% endblock %}